# fly.toml file generated for pflserver on 2023-04-16T23:56:34-05:00

app = "pflserver"
primary_region = "lax"

[http_service]
  internal_port = 8080
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
